-- DROP AND CREATE EMPLOYEE_INFO_DB
DROP DATABASE IF EXISTS employee_info_db;
CREATE database employee_info_db;

-- CREATE TABLES WITHIN DATABASE
USE employee_info_db;

-- CREATE EMPLOYEE TABLE
CREATE TABLE employee (
	id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NOT NULL,
    manager_id INT NOT NULL,
	PRIMARY KEY (id)
);

-- CREATE ROLE TABLE
CREATE TABLE role (
	id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL (12, 2) NULL,
    department_id INT NOT NULL,
	PRIMARY KEY (id)
);

-- CREATE DEPARTMENT TABLE
CREATE TABLE department (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
	PRIMARY KEY (id)
    );
